### PR TITLE
fix: Make SellerStore async

### LINKED ISSUE #138: Make abstract SellerStore methods async
#111 made most things async, but I think SellerStore got missed from the sweep?  

https://github.com/openactive/OpenActive.Server.NET/blob/6b3680986424a0baeb2462f44d97cc17c39b0707/OpenActive.Server.NET/OpenBookingHelper/Stores/SellerStore.cs#L29-L35

Should be changed to be `Task<ILegalEntity>` returning and have `Async` appended.

### PR DESCRIPTION
**Pull request by matdavies**
Fixes #138

### CODE REVIEW

File: Examples/BookingSystem.AspNetCore/Stores/SellerStore.cs [hunk 1]
```diff
@@ -22,13 +23,13 @@ public AcmeSellerStore(bool useSingleSellerMode)
...
         // If the Seller is not found, simply return null to generate the correct Open Booking error
-        protected override ILegalEntity GetSeller(SellerIdComponents sellerIdComponents)
+        protected override ValueTask<ILegalEntity> GetSellerAsync(SellerIdComponents sellerIdComponents)
         {
             // Note both examples are shown below to demonstrate options available. Only one block of the if statement below is required for an actual implementation.
             if (_useSingleSellerMode)
             {
                 // For Single Seller booking systems, no ID will be available from sellerIdComponents, and this data should instead come from your configuration table
-                return new Organization
+                return new ValueTask<ILegalEntity>(new Organization
```
Comment (nickevansuk) [inline Examples/BookingSystem.AspNetCore/Stores/SellerStore.cs:32]: This shouldn't need to be a ValueTask as it's a static value, only the interface needs this and .NET should do some magic to figure out to return one

```suggestion
                return new Organization
```

File: Examples/BookingSystem.AspNetCore/Stores/SellerStore.cs [hunk 2]
```diff
@@ -61,51 +62,53 @@ protected override ILegalEntity GetSeller(SellerIdComponents sellerIdComponents)
                 var seller = db.SingleById<SellerTable>(sellerIdComponents.SellerIdLong);
                 if (seller == null)
                 {
-                    return null;
+                    return new ValueTask<ILegalEntity>((ILegalEntity) null);
```
Comment (nickevansuk) [inline Examples/BookingSystem.AspNetCore/Stores/SellerStore.cs:65]: Same issue here
```suggestion
                    return null;
```

File: Examples/BookingSystem.AspNetCore/Stores/SellerStore.cs [hunk 3]
```diff
@@ -22,13 +23,13 @@ public AcmeSellerStore(bool useSingleSellerMode)
         }
 
         // If the Seller is not found, simply return null to generate the correct Open Booking error
-        protected override ILegalEntity GetSeller(SellerIdComponents sellerIdComponents)
+        protected override ValueTask<ILegalEntity> GetSellerAsync(SellerIdComponents sellerIdComponents)
```
Comment (nickevansuk) [inline Examples/BookingSystem.AspNetCore/Stores/SellerStore.cs:26]: Need the `async` keyword so .NET can do its magic on the return values
```suggestion
        protected async override ValueTask<ILegalEntity> GetSellerAsync(SellerIdComponents sellerIdComponents)
```

File: Examples/BookingSystem.AspNetCore/Stores/SellerStore.cs [hunk 4]
```diff
@@ -61,51 +62,53 @@ protected override ILegalEntity GetSeller(SellerIdComponents sellerIdComponents)
...
+                                RequiresExplicitConsent = false
+                            }
+                        },
+                        IsOpenBookingAllowed = true,
+                    });
             }
         }
     }
-}
+}
```
Comment (nickevansuk) [inline Examples/BookingSystem.AspNetCore/Stores/SellerStore.cs:114]: Potentially based on the above all this can be reverted?

File: OpenActive.Server.NET/CustomBookingEngine/CustomBookingEngine.cs [hunk 5]
```diff
@@ -327,7 +327,7 @@ private async Task<RpdePage> RenderOrdersRPDEPageForFeed(OrderType feedType, str
 
         public async Task<ResponseContent> GetOrderStatus(string clientId, Uri sellerId, string uuid)
         {
-            var (orderId, sellerIdComponents, seller) = ConstructIdsFromRequest(clientId, sellerId, uuid, OrderType.Order);
+            var (orderId, sellerIdComponents, seller) = await ConstructIdsFromRequestAsync(clientId, sellerId, uuid, OrderType.Order);
```
Comment (nickevansuk) [inline OpenActive.Server.NET/CustomBookingEngine/CustomBookingEngine.cs:330]:
```suggestion
            var (orderId, sellerIdComponents, seller) = await ConstructIdsFromRequest(clientId, sellerId, uuid, OrderType.Order);
```

We've not been using naming convention here on the basis that the ValueTask pattern doesn't allow two methods to exist (one sync and one async) but rather one method that serves both needs - so this makes the code more readable

File: OpenActive.Server.NET/CustomBookingEngine/CustomBookingEngine.cs [hunk 6]
```diff
@@ -690,7 +690,7 @@ async Task<ResponseContent> IBookingEngine.TriggerTestAction(string actionJson)
 
             SellerIdComponents sellerIdComponents = GetSellerIdComponentsFromApiKey(authenticationSellerId);
 
-            ILegalEntity seller = settings.SellerStore.GetSellerById(sellerIdComponents);
+            ILegalEntity seller = await settings.SellerStore.GetSellerByIdAsync(sellerIdComponents);
```
Comment (nickevansuk) [inline OpenActive.Server.NET/CustomBookingEngine/CustomBookingEngine.cs:693]:
```suggestion
            ILegalEntity seller = await settings.SellerStore.GetSellerById(sellerIdComponents);
```
As above

File: OpenActive.Server.NET/OpenBookingHelper/Stores/SellerStore.cs [hunk 7]
```diff
@@ -26,13 +27,12 @@ protected Uri RenderSingleSellerId()
             return this.IdTemplate.RenderId(new SellerIdComponents());
         }
 
-        internal ILegalEntity GetSellerById(SellerIdComponents sellerIdComponents)
+        internal ValueTask<ILegalEntity> GetSellerByIdAsync(SellerIdComponents sellerIdComponents)
```
Comment (nickevansuk) [inline OpenActive.Server.NET/OpenBookingHelper/Stores/SellerStore.cs:30]:
```suggestion
        internal async ValueTask<ILegalEntity> GetSellerById(SellerIdComponents sellerIdComponents)
```
As above

File: OpenActive.Server.NET/CustomBookingEngine/CustomBookingEngine.cs [hunk 8]
```diff
@@ -677,7 +677,7 @@ async Task<ResponseContent> IBookingEngine.TriggerTestAction(string actionJson)
 
         protected abstract Task TriggerTestAction(OpenBookingSimulateAction simulateAction, OrderIdTemplate orderIdTemplate);
 
-        private (OrderIdComponents orderId, SellerIdComponents sellerIdComponents, ILegalEntity seller) ConstructIdsFromRequest(string clientId, Uri authenticationSellerId, string uuid, OrderType orderType)
+        private async Task<(OrderIdComponents orderId, SellerIdComponents sellerIdComponents, ILegalEntity seller)> ConstructIdsFromRequestAsync(string clientId, Uri authenticationSellerId, string uuid, OrderType orderType)
```
Comment (nickevansuk) [inline OpenActive.Server.NET/CustomBookingEngine/CustomBookingEngine.cs:680]:
```suggestion
        private async Task<(OrderIdComponents orderId, SellerIdComponents sellerIdComponents, ILegalEntity seller)> ConstructIdsFromRequest(string clientId, Uri authenticationSellerId, string uuid, OrderType orderType)
```

As above

**Review by nickevansuk — CHANGES_REQUESTED** [review]
Not so big after all

File: OpenActive.Server.NET/OpenBookingHelper/Stores/SellerStore.cs [hunk 9]
```diff
@@ -26,13 +27,13 @@ protected Uri RenderSingleSellerId()
             return this.IdTemplate.RenderId(new SellerIdComponents());
         }
 
-        internal ILegalEntity GetSellerById(SellerIdComponents sellerIdComponents)
+        internal ValueTask<ILegalEntity> GetSellerById(SellerIdComponents sellerIdComponents)
         {
             // TODO: Include validation on the OrderItem created, to ensure it includes all the required fields
             return GetSeller(sellerIdComponents);
         }
```
Comment (nickevansuk) [inline OpenActive.Server.NET/OpenBookingHelper/Stores/SellerStore.cs:34]:
```suggestion
        internal async ValueTask<ILegalEntity> GetSellerById(SellerIdComponents sellerIdComponents)
        {
            // TODO: Include validation on the OrderItem created, to ensure it includes all the required fields
            return await GetSeller(sellerIdComponents);
        }
```

Does have we not missed one here?

**Review by nickevansuk — APPROVED** [review]
